# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://github.com/fgrehm/vagrant-cachier#quick-start
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  # Heartbreaker virtual machine
  config.vm.define "hbreaker" do |hbreaker|
    hbreaker.vm.box = "pbarriscale/centos7-gui"

    # mount 
    hbreaker.vm.synced_folder "../", "/fuzz"

    # setup and install the heartbreaker
    hbreaker.vm.provision "shell", inline: "cd /fuzz && ./setup-heartbreaker.sh"

    hbreaker.vm.network "private_network", ip: "192.168.50.151"
  end


end
